
"""from qick.asm_v2 import AveragerProgramV2
from types import SimpleNamespace

# 1. Dual Access Wrapper for QICK config
class DualAccessConfig:
    def __init__(self, data):
        self._data = data

    def __getitem__(self, key):
        return self._data[key]

    def __getattr__(self, name):
        if name in self._data:
            return self._data[name]
        raise AttributeError(f"'DualAccessConfig' object has no attribute '{name}'")

# 2. Robust time conversion helper
def mock_us2cycles(us, **kwargs):
    if hasattr(us, 'to_int'):
        return us.to_int(scale=384.0, quantize=1, parname='time')
    return int(us * 384.0)

raw_config = {
    'tprocs': [{
        'type': 'qick_processor',
        'revision': 21,        
        'pmem_size': 65536,
        'wmem_size': 65536,
        'dmem_size': 65536,
        'dreg_qty': 16,
        'output_pins': []
    }],
    'gens': [],
    'readouts': [],
    'us2cycles': mock_us2cycles  
}

dummy_soccfg = DualAccessConfig(raw_config)


# -------------------------------------------------------------------
# YOUR CUSTOM PROGRAM
# -------------------------------------------------------------------
class QTagSweepProgram(AveragerProgramV2):
    
    def _make_binprog(self):
        """ """
        OVERRIDE: This allows the text macros to expand normally, 
        but skips the final binary generation step so the desktop 
        compiler doesn't crash on the custom 'QTAG' command.
        """ """
        self.binprog = {'pmem': None, 'wmem': None, 'dmem': None}

    def _initialize(self, cfg):
        f_start = cfg["start_freq"]
        f_stop  = cfg["stop_freq"]
        avg_val = cfg["averager_value"]
        step_1  = cfg["first_sweep_step"]
        step_2  = cfg["second_sweep_step"]
        win_2   = cfg["second_sweep_window"]

        # Back to QTAG!
        self.asm_inst({'CMD': 'QTAG', 'OP': '0', 'DT1': str(f_start), 'DT2': str(f_stop), 'DT3': str(avg_val), 'DT4': str(step_1)})
        self.asm_inst({'CMD': 'QTAG', 'OP': '3', 'DT1': '0', 'DT2': str(step_2), 'DT3': str(win_2), 'DT4': '0'})

    def _body(self, cfg):
        self.asm_inst({'CMD': 'QTAG', 'OP': '1'})
        self.wait(1.0) 
        self.asm_inst({'CMD': 'QTAG', 'OP': '2'})
        
        self.write_dmem(addr=0, src='s_core_r1') 
        self.write_dmem(addr=1, src='s_core_r2') 


# -------------------------------------------------------------------
# EXECUTION
# -------------------------------------------------------------------
test_config = {
    "start_freq": 100000, 
    "stop_freq": 500000,
    "first_sweep_step": 1000,
    "second_sweep_step": 50,
    "averager_value": 16,
    "second_sweep_window": 2000
}

print("Expanding macros offline...")

# This will no longer crash, because we safely overrode the binary step
prog = QTagSweepProgram(soccfg=dummy_soccfg, reps=1, final_delay=1.0, cfg=test_config)
print("Macro expansion successful!\n")

print("--- Generated QTAG Instruction Sequence ---")

# prog.prog_list contains the exact sequence of commands generated by your class
for idx, inst in enumerate(prog.prog_list):
    print(f"Step {idx:02d}: {inst}")"""
from qick.asm_v2 import AveragerProgramV2
import numpy as np

# 1. Dual Access Wrapper for QICK config
class DualAccessConfig:
    def __init__(self, data):
        self._data = data

    def __getitem__(self, key):
        return self._data[key]

    def __getattr__(self, name):
        if name in self._data:
            return self._data[name]
        raise AttributeError(f"'DualAccessConfig' object has no attribute '{name}'")

def mock_us2cycles(us, **kwargs):
    if hasattr(us, 'to_int'):
        return us.to_int(scale=384.0, quantize=1, parname='time')
    return int(us * 384.0)

raw_config = {
    'tprocs': [{
        'type': 'qick_processor',
        'revision': 21,        
        'pmem_size': 65536,
        'wmem_size': 65536,
        'dmem_size': 65536,
        'dreg_qty': 16,
        'output_pins': []
    }],
    'gens': [],
    'readouts': [],
    'us2cycles': mock_us2cycles  
}

dummy_soccfg = DualAccessConfig(raw_config)


# -------------------------------------------------------------------
# YOUR CUSTOM PROGRAM
# -------------------------------------------------------------------
class QTagSweepProgram(AveragerProgramV2):
    
    def _initialize(self, cfg):
        # --- OPCODE 0: Set Bounds ---
        self.asm_inst({'CMD': 'REG_WR', 'DST': 's1', 'SRC': 'imm', 'LIT': f'#{cfg["start_freq"]}'})
        self.asm_inst({'CMD': 'REG_WR', 'DST': 's2', 'SRC': 'imm', 'LIT': f'#{cfg["stop_freq"]}'})
        self.asm_inst({'CMD': 'REG_WR', 'DST': 's3', 'SRC': 'imm', 'LIT': f'#{cfg["averager_value"]}'})
        self.asm_inst({'CMD': 'REG_WR', 'DST': 's4', 'SRC': 'imm', 'LIT': f'#{cfg["first_sweep_step"]}'})
        self.asm_inst({'CMD': 'PB', 'C_OP': '0', 'R1': 's1', 'R2': 's2', 'R3': 's3', 'R4': 's4'})
        
        # --- OPCODE 3: Set Sweep Steps ---
        self.asm_inst({'CMD': 'REG_WR', 'DST': 's1', 'SRC': 'imm', 'LIT': '#0'})
        self.asm_inst({'CMD': 'REG_WR', 'DST': 's2', 'SRC': 'imm', 'LIT': f'#{cfg["second_sweep_step"]}'})
        self.asm_inst({'CMD': 'REG_WR', 'DST': 's3', 'SRC': 'imm', 'LIT': f'#{cfg["second_sweep_window"]}'})
        self.asm_inst({'CMD': 'REG_WR', 'DST': 's4', 'SRC': 'imm', 'LIT': '#0'})
        self.asm_inst({'CMD': 'PB', 'C_OP': '3', 'R1': 's1', 'R2': 's2', 'R3': 's3', 'R4': 's4'})

    def _body(self, cfg):
        # Trigger the hardware (OP=1)
        self.asm_inst({'CMD': 'PB', 'C_OP': '1', 'R1': 's0', 'R2': 's0', 'R3': 's0', 'R4': 's0'})
        
        self.wait(1.0) 
        
        # Read the outputs (OP=2)
        self.asm_inst({'CMD': 'PB', 'C_OP': '2', 'R1': 's0', 'R2': 's0', 'R3': 's0', 'R4': 's0'})
        
        self.write_dmem(addr=0, src='s_core_r1') 
        self.write_dmem(addr=1, src='s_core_r2') 

    # -------------------------------------------------------------------
    # TA'S ASSEMBLY CODE EXTRACTOR
    # -------------------------------------------------------------------
    def export_assembly(self):
        """
        Translates the internal Python compiler dictionaries into 
        standard, readable tProc Assembly Code.
        """
        asm_text = "// --- tProc V2 Assembly Code for Custom Module ---\n"
        asm_text += "// Generated by QICK Python Assembler\n\n"
        
        for idx, inst in enumerate(self.prog_list):
            cmd = inst.get('CMD')
            line = f"[{idx:03d}]: "
            
            # Format standard register writes
            if cmd == 'REG_WR':
                dst = inst.get('DST')
                lit = inst.get('LIT')
                line += f"REG_WR  {dst}, {lit}"
                
            # Format the Peripheral Bus command
            elif cmd == 'PB':
                op = inst.get('C_OP')
                r1 = inst.get('R1', 's0')
                r2 = inst.get('R2', 's0')
                r3 = inst.get('R3', 's0')
                r4 = inst.get('R4', 's0')
                line += f"PB      {op}, {r1}, {r2}, {r3}, {r4}"
                
            # Format the Wait command
            elif cmd == 'WAIT':
                time_val = inst.get('TIME', '@0')
                line += f"WAIT    {time_val}"
                
            # Format Data Memory Writes
            elif cmd == 'DMEM_WR':
                addr = inst.get('ADDR', '0')
                src = inst.get('SRC', 's_core_r1')
                line += f"DMEM_WR [{addr}], {src}"
                
            else:
                line += f"{cmd} {inst}"
                
            asm_text += line + "\n"

        # Save to a .asm file
        with open("qtag_program.asm", "w") as file:
            file.write(asm_text)
        print("[+] Dumped readable Assembly Code to 'qtag_program.asm'")


# -------------------------------------------------------------------
# EXECUTION & HEX DUMP
# -------------------------------------------------------------------
test_config = {
    "start_freq": 100000, 
    "stop_freq": 500000,
    "first_sweep_step": 1000,
    "second_sweep_step": 50,
    "averager_value": 16,
    "second_sweep_window": 2000
}

print("Compiling assembly to binary machine code...")

prog = QTagSweepProgram(soccfg=dummy_soccfg, reps=1, final_delay=1.0, cfg=test_config)
print("Compilation successful!\n")

# 1. Generate the TA's readable Assembly Code (.asm)
prog.export_assembly()

# 2. Generate the real PMEM Hex for Vivado Simulation (.mem)
pmem_hex = ""
for hex_line in prog.binprog['pmem']:
    if isinstance(hex_line, (list, np.ndarray)):
        val = (int(hex_line[2]) << 64) | (int(hex_line[1]) << 32) | int(hex_line[0])
    else:
        val = hex_line
    pmem_hex += f"{val:018x}\n"

with open("qtag_pmem_for_vivado.mem", "w") as file:
    file.write(pmem_hex)
print("[+] Saved real machine code to 'qtag_pmem_for_vivado.mem'")