// --- tProc V2 Assembly Code for Custom Module ---
// Generated by QICK Python Assembler

[000]: NOP {'CMD': 'NOP', 'P_ADDR': 0}
[001]: REG_WR  s12, #0
[002]: REG_WR  s1, #100000
[003]: REG_WR  s2, #500000
[004]: REG_WR  s3, #16
[005]: REG_WR  s4, #1000
[006]: PB      0, s1, s2, s3, s4
[007]: REG_WR  s1, #0
[008]: REG_WR  s2, #50
[009]: REG_WR  s3, #2000
[010]: REG_WR  s4, #0
[011]: PB      3, s1, s2, s3, s4
[012]: REG_WR  r0, #0
[013]: PB      1, s0, s0, s0, s0
[014]: REG_WR  s15, None
[015]: WAIT    @384
[016]: PB      2, s0, s0, s0, s0
[017]: DMEM_WR [0], op
[018]: DMEM_WR [0], op
[019]: REG_WR  s12, None
[020]: REG_WR  s15, None
[021]: TEST {'CMD': 'TEST', 'OP': 'r0 - #0', 'P_ADDR': 22, 'LINE': 22}
[022]: JUMP {'CMD': 'JUMP', 'ADDR': 's15', 'IF': 'NZ', 'WR': 'r0 op', 'OP': 'r0 + #1', 'P_ADDR': 23, 'LINE': 23}
[023]: REG_WR  s15, None
[024]: JUMP {'CMD': 'JUMP', 'ADDR': 's15', 'P_ADDR': 25, 'LINE': 25}
